# -*- coding: utf-8 -*-
"""ds_bike sharing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VK4kv5lgNLQYNu613aloEb1DV5exWXPX
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import streamlit as st
from babel.numbers import format_currency
sns.set(style='dark')

# Commented out IPython magic to ensure Python compatibility.
# %%writefile ds_bike_sharing.py